set number
set cursorline      " highlight current line
set laststatus=2    " always show the statusline
set background=dark
set t_Co=256        " colors!
set mouse=a         " enable mouse
set noswapfile      " no .swp files
set autoread        " detect whether a file has been changed from the outside
set expandtab
set shiftwidth=4    " 4 space shift
set tabstop=4       " 4 space tab
set smarttab
set linebreak       " break long lines
set textwidth=500
set showmatch       " set show matching parenthesis
set hlsearch        " highlight search terms
set incsearch       " incremental search
set softtabstop=4
set autoindent
syntax on           " enable syntax hl

" VIM theme
let g:airline_theme='angr'

" key mappings
:noremap <C-P> :FZF<CR> " Map CTRL+P toFZF command file search

" ============================================

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'

call plug#begin('~/.vim/plugged')

" Make sure you use single quotes
Plug '~/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
Plug 'crusoexia/vim-monokai'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Initialize plugin system
call plug#end()

colorscheme monokai
