wtf:
  # Will fail if not defined:
  colors:
  refreshInterval: 5
  mods:
    cmdrunner:
      enabled: true
      type: cmdrunner
      refreshInterval: 10
      title: 'Dev Status'
      cmd: "node"
      args: ["/Users/jordid/GitHome/ma-status/run.js"]
      position:
        top: 0
        left: 0
        height: 1
        width: 1
    cmdrunner2:
      enabled: true
      type: cmdrunner
      refreshInterval: 10
      title: 'Staging status'
      cmd: 'node'
      args: ["/Users/jordid/GitHome/ma-status/run.js", 'staging']
      position:
        top: 0
        left: 1
        height: 1
        width: 1


